import './globals.css';
import { Roboto, Montserrat } from 'next/font/google';
import Layout from '@/components/layout/Layout';
import Providers from '@/utils/Providers';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['300', '400', '500', '700'],
    style: ['normal', 'italic'],
});

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['300', '400', '500', '700'],
    style: ['normal', 'italic'],
});

export const metadata = {
    title: 'Fiverr',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en' suppressHydrationWarning={true}>
            <body className={`${roboto.className} ${montserrat.className}`}>
                <Providers>
                    <Layout>{children}</Layout>
                    <ToastContainer />
                </Providers>
            </body>
        </html>
    );
}
